init:
  doneCounter: 0
  parentIndex: ${parent.index}
  monitorURL: https://${region}-${projectID}.cloudfunctions.net/BqMonitor
  self.i: 1
  self.cnt: 0

  unique: $rand



pipeline:
  prepare:
    init-db:
      action: dsunit:init
      datastore: bqtail
      expand: true
      config:
        driverName: bigquery
        credentials: $gcpCredentials
        parameters:
          datasetId: bqtail
      scripts:
        - URL: ${parent.path}/bqtail/schema.sql
    populate:
      bqtail:
        action: dsunit:prepare
        expand: true
        datastore: bqtail
        URL:  ${parent.path}/bqtail/prepare

  cleanUp:
    action: storage:remove
    sleepTimeMs: 1000
    assets:
      - URL: 'gs://${configBucket}/BqTail/_.cache'
        credentials: $gcpCredentials
      - URL: 'gs://${configBucket}/BqTail/Rules/case_${parent.index}/'
        credentials: $gcpCredentials
      - URL: 'gs://${opsBucket}/BqTail/errors/'
        credentials: $gcpCredentials

  setupRule:
    action: storage:copy
    expand: true
    source:
      URL: ${parent.path}/rule
    dest:
      credentials: $gcpCredentials
      URL: gs://${configBucket}/BqTail/Rules/case_${parent.index}


  trigger:
    generate:
      action: storage:generate
      fileCount: 20
      inBackground: true
      indexVariable: id
      lines: 1
      index: ${self.i}
      lineTemplate: '{"id": ${id}, "name": "dummy ${id}", "type_id": 1}'
      dest:
        URL: gs://${triggerBucket}/data/case${parentIndex}/2020/01/01/dummy_${unique}_${self.cnt++}_$fileNo.json
        credentials: $gcpCredentials
    inc:
      action: nop
      sleepTimeMs: 700
      logging: false
      init:
        'self.i': ${self.i+20}

    goto:
      when: ${self.i} < 1000
      action: goto
      task: trigger



  waitForServerless:
    action: nop
    sleepTimeMs: 10000


  waitForDone:
    listDone:
      init:
        _: $doneCounter++
      action: storage:list
      sleepTimeMs: 10000
      match:
        Filter: 'dummy_v${parentIndex}'
      source:
        Credentials: $gcpCredentials
        URL: 'gs://${opsBucket}/BqTail/Journal/Running'

    checkDone:
      action: goto
      when: $Len(${listDone.Assets}) > 0 && $doneCounter < 20
      task: waitForDone


  waitForCompletion:
    action: nop
    sleepTimeMs: 10000


  validate:
    check-db:
      bqtail:
        action: dsunit:expect
        expand: true
        datastore: bqtail
        URL:  ${parent.path}/bqtail/expect
