

pipeline:
  prepare:
    init-db:
      action: dsunit:init
      datastore: bqtail
      config:
        driverName: bigquery
        credentials: $gcpCredentials
        parameters:
          datasetId: bqtail
      scripts:
        - URL: ${parent.path}/bqtail/schema.sql
    populate:
      bqtail:
        action: dsunit:prepare
        datastore: bqtail
        URL:  ${parent.path}/bqtail/prepare

  setupRule:
    action: storage:copy
    expand: true
    source:
      URL: ${parent.path}/rule.json
    dest:
      credentials: $gcpCredentials
      URL: gs://${configBucket}/BqTail/Rules/case_${parent.index}.json

  trigger:
    action: storage:copy
    sleepTimeMs: 10000
    source:
      URL: ${parent.path}/data/trigger/dummy.json
    dest:
      URL: gs://${triggerBucket}/data/case013/dummy.json
      credentials: $gcpCredentials

