init:
  doneCounter: 0
  parentIndex: ${parent.index}
  bqtailCmd: ${appPath}/cmd/bqtail/bqtail

pipeline:
  prepare:
    init-db:
      action: dsunit:init
      datastore: bqtail
      expand: true
      config:
        driverName: bigquery
        credentials: $gcpCredentials
        parameters:
          datasetId: bqtail
      scripts:
        - URL: ${parent.path}/bqtail/schema.sql
    populate:
      bqtail:
        action: dsunit:prepare
        datastore: bqtail
        URL:  ${parent.path}/bqtail/prepare


  uploadData:
    action: storage:copy
    source:
      URL: ${parent.path}/data/trigger/
    dest:
      URL: gs://${triggerBucket}/data/case${parent.index}/
      credentials: $gcpCredentials



  trigger:
    action: exec:run
    checkError: true
    commands:
      - export GOOGLE_APPLICATION_CREDENTIALS='${env.HOME}/.secret/${gcpCredentials}.json'
      - ${bqtailCmd} -r='${parent.path}/rule/rule.yaml' -s='gs://${triggerBucket}/data/case${parent.index}/'

  validate:
    check-db:
      bqtail:
        action: dsunit:expect
        datastore: bqtail
        URL:  ${parent.path}/bqtail/expect
