

pipeline:
  prepare:
    init-db:
      action: dsunit:init
      datastore: bqtail
      config:
        driverName: bigquery
        credentials: $gcpCredentials
        parameters:
          datasetId: bqtail
      scripts:
        - URL: ${parent.path}/bqtail/schema.sql
    populate:
      bqtail:
        action: dsunit:prepare
        datastore: bqtail
        URL:  ${parent.path}/bqtail/prepare


  upload:
    action: storage:copy
    source:
      URL: ${parent.path}/data/trigger/
    dest:
      URL: gs://${triggerBucket}/data/case016/
      credentials: $gcpCredentials


  trigger:
    action: storage:copy
    expand: true
    source:
      URL: ${parent.path}/replay.json
    dest:
      credentials: $gcpCredentials
      URL: gs://${triggerBucket}/_load_/case_${parent.index}.json


  waitForServerless:
    action: nop
    sleepTimeMs: 65000


  validate:
    check-db:
      action: dsunit:expect
      datastore: bqtail
      URL:  ${parent.path}/bqtail/expect
