init:
  appPath: $WorkingDirectory(..)
  target:
    URL: ssh://127.0.0.1/
    credentials: localhost
  gcpSecrets: gcp-e2e
  gcp: ${secrets.$gcpSecrets}
  projectID: $gcp.ProjectID
  serviceAccount: $gcp.ClientEmail

defaults:
  credentials: $gcpSecrets

pipeline:

  deploy:
    package:
      action: exec:run
      comments: vendor build for deployment speedup
      target: $target
      checkError: true
      commands:
        - export GIT_TERMINAL_PROMPT=1
        - export GO111MODULE=on
        - unset GOPATH
        - cd ${appPath}/
        - go mod vendor
        - go build


    upload:
      action: gcp/cloudfunctions:deploy
      '@name': SiteListBQTail
      timeout: 180s
      public: true
      availableMemoryMb: 256
      entryPoint: BQTailFn
      runtime: go111
      environmentVariables:
        CONFIG: gs://sitelist/config/bqtail.json
      eventTrigger:
        eventType: google.storage.object.finalize
        resource: projects/_/buckets/sitelist
      source:
        URL: ${appPath}/
