defaults:
  credentials: $gcpSecrets

pipeline:
#  undeploy:
#    tail:
#      action: gcp/cloudfunctions:delete
#      '@name': E2eDataBqTail
#    dispatch:
#      action: gcp/cloudfunctions:delete
#      '@name': BqDispatch


  deploy:
    package:
      action: exec:run
      comments: vendor build for deployment speedup
      target: $target
      checkError: true
      commands:
        - export GIT_TERMINAL_PROMPT=1
        - export GO111MODULE=on
        - unset GOPATH
        - cd ${appPath}/
        - go mod vendor
        - go build

    loadConifg:
      action: nop
      init:
        configText: $Cat('config/config.json')
        config: $AsMap(${configText})

    deploay:
      bqtail:
        action: gcp/cloudfunctions:deploy
        '@name': E2eDataBqTail
        timeout: 180s
        public: true
        availableMemoryMb: 512
        entryPoint: BqTailFn
        runtime: go111
        serviceAccountEmail: ${gcp.serviceAccount}
        environmentVariables:
          CONFIG: ${config.BqTailConfigURL}
        eventTrigger:
          eventType: google.storage.object.finalize
          resource: projects/_/buckets/${config.Bucket}
        source:
          URL: ${appPath}/

      bqdisaptch:
        action: gcp/cloudfunctions:deploy
        '@name': BqDispatch
        timeout: 180s
        public: true
        serviceAccountEmail: ${gcp.serviceAccount}
        availableMemoryMb: 512
        entryPoint: BqDispatchFn
        runtime: go111
        environmentVariables:
          CONFIG: ${config.BqDispatchConfigURL}
        eventTrigger:
          eventType: google.cloud.bigquery.job.complete
          resource: projects/${projectID}/jobs/{jobId}
        source:
          URL: ${appPath}/

