init:
  target:
    URL: ssh://127.0.0.1/
    credentials: localhost
  appHost: $Hostname($target.URL)
  appPath: $WorkingDirectory(..)

  gcpCredentials: gcp-e2e
  gcp: ${secrets.$gcpCredentials}
  projectID: $gcp.ProjectID
  prefix: $Replace($projectID,'-','_')
  serviceAccount: $gcp.ClientEmail

  configBucket: ${prefix}_config
  triggerBucket: ${prefix}_bqtail
  dispatchBucket: ${prefix}_bqdispatch
  opsBucket: ${prefix}_operations
  exportBucket: ${prefix}_export

pipeline:

  init:
    system:
      action: run
      request: '@system'
      tasks: '*'
    app:
      action: run
      request: '@app'
      tasks: 'deploy'

  test:
    action: run
    request: '@regression/regression'
    tasks: '*'
