pipeline:

  set_sdk:
    action: sdk.set
    target: $target
    sdk: go:1.14

  package:
    action: exec:run
    target: $target
    checkError: true
    commands:
      - export GIT_TERMINAL_PROMPT=1
      - export GO111MODULE=on
      - unset GOPATH
      - cd ${appPath}/
      - go mod vendor
      - echo 'apply cloud functiion hack'
      - mkdir -p vendor/github.com/viant/bqtail
      - cp -rf base vendor/github.com/viant/bqtail
      - cp -rf dispatch vendor/github.com/viant/bqtail
      - cp -rf mon vendor/github.com/viant/bqtail
      - cp -rf service vendor/github.com/viant/bqtail
      - cp -rf s* vendor/github.com/viant/bqtail/
      - cp -rf t* vendor/github.com/viant/bqtail/
      - cp -rf a* vendor/github.com/viant/bqtail/
      - go build

  bqtail:
    action: gcp/cloudfunctions:deploy
    credentials: $gcpCredentials
    '@name': BqTail
    timeout: 540s
    public: true
    availableMemoryMb: 256
    entryPoint: BqTail
    retry: true
    runtime: go111
    serviceAccountEmail: ${gcp.serviceAccount}
    environmentVariables:
      CONFIG: gs://${configBucket}/BqTail/config.json
      LOGGING: false
      GS_MAX_RETRIES: 10
      MAX_RETRIES: 10
    eventTrigger:
      eventType: google.storage.object.finalize
      resource: projects/_/buckets/${triggerBucket}
    source:
      URL: ${appPath}

  bqdisaptch:
    action: gcp/cloudfunctions:deploy
    credentials: $gcpCredentials
    '@name': BqDispatch
    timeout: 59s
    public: true
    serviceAccountEmail: ${gcp.serviceAccount}
    availableMemoryMb: 256
    entryPoint: BqDispatch
    runtime: go111
    environmentVariables:
      CONFIG: gs://${configBucket}/BqDispatch/config.json
      LOGGING: false
      GS_MAX_RETRIES: 10
      MAX_RETRIES: 10
    source:
      URL: ${appPath}

