pipeline:
  bqtail:
    action: gcp/cloudfunctions:deploy
    credentials: $gcpCredentials
    '@name': BqTail
    timeout: 540s
    public: true
    retry: true
    availableMemoryMb: 128
    entryPoint: BqTail
    runtime: go111
    serviceAccountEmail: ${gcp.serviceAccount}
    environmentVariables:
      CONFIG: gs://${configBucket}/BqTail/config.json
      LOGGING: false
    eventTrigger:
      eventType: google.storage.object.finalize
      resource: projects/_/buckets/${triggerBucket}
    source:
      URL: ${appPath}

  bqdisaptch:
    action: gcp/cloudfunctions:deploy
    '@name': BqDispatch
    timeout: 540s
    public: true
    serviceAccountEmail: ${gcp.serviceAccount}
    availableMemoryMb: 128
    entryPoint: BqDispatch
    runtime: go111
    environmentVariables:
      CONFIG: gs://${configBucket}/BqDispatch/config.json
      LOGGING: false
    eventTrigger:
      eventType: google.cloud.bigquery.job.complete
      resource: projects/${projectID}/jobs/{jobId}
    source:
      URL: ${appPath}

