pipeline:

  set_sdk:
    action: sdk.set
    target: $target
    sdk: go:1.12

  package:
    action: exec:run
    target: $target
    checkError: true
    commands:
      - cd $appPath
      - export GIT_TERMINAL_PROMPT=1
      - export GO111MODULE=on
      - unset GOPATH
      - go mod vendor
      - go build

  bqtail:
    action: gcp/cloudfunctions:deploy
    credentials: $gcpCredentials
    '@name': BqTail
    timeout: 540s
    public: true
    availableMemoryMb: 128
    entryPoint: BqTail
    retry: true
    runtime: go111
    serviceAccountEmail: ${gcp.serviceAccount}
    environmentVariables:
      CONFIG: gs://${configBucket}/BqTail/config.json
      LOGGING: false
      GS_MAX_RETRIES: 5
    eventTrigger:
      eventType: google.storage.object.finalize
      resource: projects/_/buckets/${triggerBucket}
    source:
      URL: ${appPath}

#  bqdisaptch:
#    action: gcp/cloudfunctions:deploy
#    credentials: $gcpCredentials
#    '@name': BqDispatch
#    timeout: 59s
#    public: true
#    serviceAccountEmail: ${gcp.serviceAccount}
#    availableMemoryMb: 128
#    entryPoint: BqDispatch
#    runtime: go111
#    environmentVariables:
#      CONFIG: gs://${configBucket}/BqDispatch/config.json
#      LOGGING: false
#      GS_MAX_RETRIES: 20
#    source:
#      URL: ${appPath}
#
#  schedule:
#    action: gcp/cloudscheduler:deploy
#    credentials: $gcpCredentials
#    name: BqDispatch
#    schedule: '*/1 * * * *'
#    body: {}
#    timeZone: GMT
#    httpTarget:
#      headers:
#        User-Agent: Google-Cloud-Scheduler
#      httpMethod: POST
#      uri: https://${region}-${gcp.ProjectID}.cloudfunctions.net/BqDispatch