init:
  appPath: $WorkingDirectory(..)
  target:
    URL: ssh://127.0.0.1/
    credentials: localhost
  gcpSecrets: gcp-e2e
  gcp: ${secrets.$gcpSecrets}
  projectID: $gcp.ProjectID
  serviceAccount: $gcp.ClientEmail

defaults:
  credentials: $gcpSecrets

pipeline:

    package:
      action: exec:run
      comments: vendor build for deployment speedup
      target: $target
      checkError: true
      commands:
        - export GIT_TERMINAL_PROMPT=1
        - export GO111MODULE=on
        - unset GOPATH
        - cd ${appPath}/
        - go mod vendor
        - go build

    uploadConfig:
      tail:
        action: storage:copy
        source:
          URL: config/tail.json
        dest:
          URL: gs://myconfigbucket/config/tail.json
      dispatch:
        action: storage:copy
        source:
          URL: config/dispatch.json
        dest:
          URL: gs://myconfigbucket/config/dispatch.json


    deploy:
      tail:
        action: gcp/cloudfunctions:deploy
        '@name': MyDataBucketBqTail
        timeout: 540s
        public: true
        availableMemoryMb: 256
        entryPoint: BqTail
        runtime: go111
        environmentVariables:
          CONFIG: gs://myconfigbucket/config/tail.json
        eventTrigger:
          eventType: google.storage.object.finalize
          resource: projects/_/buckets/mydatabucket
        source:
          URL: ${appPath}/


      dispach:
        action: gcp/cloudfunctions:deploy
        '@name': BqDispatch
        timeout: 540s
        public: true
        availableMemoryMb: 256
        entryPoint: BqDispatch
        runtime: go111
        environmentVariables:
          CONFIG: gs://myconfigbucket/config/dispatch.json
        eventTrigger:
          eventType: google.cloud.bigquery.job.complete
          resource: projects/${projectID}/jobs/{jobId}
        source:
          URL: ${appPath}/
