pipeline:
  bqtail:
    action: gcp/cloudfunctions:deploy
    '@name': BqTail
    timeout: 540s
    public: true
    availableMemoryMb: 256
    entryPoint: BqTail
    runtime: go111
    serviceAccountEmail: ${gcp.serviceAccount}
    environmentVariables:
      CONFIG: gs://${config.bucket}/config/bqtail.json
    eventTrigger:
      eventType: google.storage.object.finalize
      resource: projects/_/buckets/${config.bucket}-inbound
    source:
      URL: ${appPath}

  bqdisaptch:
    action: gcp/cloudfunctions:deploy
    '@name': BqDispatch
    timeout: 540s
    public: true
    serviceAccountEmail: ${gcp.serviceAccount}
    availableMemoryMb: 256
    entryPoint: BqDispatch
    runtime: go111
    environmentVariables:
      CONFIG: gs://${config.bucket}/config/bqdispatch.json
    eventTrigger:
      eventType: google.cloud.bigquery.job.complete
      resource: projects/${projectID}/jobs/{jobId}
    source:
      URL: ${appPath}

