init:

  bqTail: $Cat('config/tail.json')
  bqTailConfig:  $AsString($bqTail)

  bqDispatch: $Cat('config/dispatch.json')
  bqDispatchConfig:  $AsString($bqDispatch)

pipeline:

#  createBuckets:
#    configBucket:
#      action: storage:create
#      isDir: true
#      dest:
#        URL: gs://${config.configBucket}/
#        credentials: $gcpCredentials
#
#    opsBucket:
#      action: storage:create
#      isDir: true
#      dest:
#        URL: gs://${config.opsBucket}/
#        credentials: $gcpCredentials
#
#    triggerBucket:
#      action: storage:create
#      isDir: true
#      dest:
#        URL: gs://${config.triggerBucket}/
#        credentials: $gcpCredentials
#
#    dispatchBucket:
#      action: storage:create
#      isDir: true
#      dest:
#        URL: gs://${config.dispatchBucket}/
#        credentials: $gcpCredentials

  uploadConfigs:
    bqTail:
      action: storage:upload
      sourceKey: bqTailConfig
      dest:
        URL: gs://${configBucket}/BqTail/config.json
        credentials: $gcpCredentials

    bqDispatch:
      action: storage:upload
      sourceKey: bqDispatchConfig
      dest:
        URL: gs://${configBucket}/BqDispatch/config.json
        credentials: $gcpCredentials

  clearCache:
    action: storage:remove
    sleepTimeMs: 1000
    assets:
      - URL: gs://${configBucket}/BqTail/_.cache
        credentials: $gcpCredentials
