init:
  appPath: /tmp/build/bqtail
  '!gcpCredentials': $params.authWith
  gcp: ${secrets.$gcpCredentials}
  projectID: $gcp.ProjectID
  configText: $Cat('meta/config.json')
  config: $AsMap(${configText})

  bucketPrefix: $Replace(${projectID},'-','_')
  configBucket: ${bucketPrefix}_config
  triggerBucket: ${bucketPrefix}_bqtail
  opsBucket: ${bucketPrefix}_operations
  dispatchBucket: ${bucketPrefix}_bqdispatch

pipeline:
  init:
    action: run
    request: '@init'

  build:
    action: run
    request: '@build'

  deploy:
    action: run
    request: '@deploy'
