init:
  appPath: /tmp/build/bqtail
  '!region': $params.region
  '!gcpCredentials': $params.authWith
  gcp: ${secrets.$gcpCredentials}
  projectID: $gcp.ProjectID
  configText: $Cat('meta/config.json')
  config: $AsMap(${configText})


  prefix: $Replace(${projectID},'-','_')
  configBucket: ${prefix}_config
  triggerBucket: ${prefix}_bqtail
  opsBucket: ${prefix}_operation
  dispatchBucket: ${prefix}_bqdispatch
  mirrorBucket: ${prefix}_trigger

  target:
    URL: ssh://127.0.0.1/
    credentials: localhost


pipeline:
  init:
    action: run
    request: '@init'

  build:
    action: run
    request: '@build'

  deploy:
    action: run
    request: '@deploy'

  cron:
    action: gcp/cloudscheduler:deploy
    credentials: $gcpCredentials
    name: BqDispatch
    schedule: '*/1 * * * *'
    body: {}
    timeZone: GMT
    httpTarget:
      headers:
        User-Agent: Google-Cloud-Scheduler
      httpMethod: POST
      uri: https://${region}-${gcp.ProjectID}.cloudfunctions.net/BqDispatch