init:
  appPath: /tmp/build/bqtail
  '!gcpCredentials': $params.authWith
  gcpMap: $AsMap($Cat($gcpCredentials))
  projectID: $gcpMap.project_id

  configText: $Cat('meta/config.json')
  config: $AsMap(${configText})

  bucketPrefix: $Replace(${projectID},'-','_')

pipeline:
  init:
    action: run
    request: '@init'

  build:
    action: run
    request: '@build'

  deploy:
    action: run
    request: '@deploy'
