init:
  appPath: /tmp/build/bqtail
  '!gcpCredentials': $params.authWith
  gcp: ${secrets.$gcpCredentials}
  projectID: $gcp.ProjectID
  configText: $Cat('meta/config.json')
  config: $AsMap(${configText})


  prefix: $Replace(${projectID},'-','_')
  configBucket: ${prefix}_config
  triggerBucket: ${prefix}_bqtail
  opsBucket: ${prefix}_operations
  dispatchBucket: ${prefix}_bqdispatch

pipeline:
  init:
    action: run
    request: '@init'

  build:
    action: run
    request: '@build'

  deploy:
    action: run
    request: '@deploy'
