init:
  parentIndex: ${parent.index}

pipeline:

  cleanUp:
    action: storage:remove
    sleepTimeMs: 1000
    assets:
      - URL: 'gs://${configBucket}/BqTail/_.cache'
        credentials: $gcpCredentials
      - URL: 'gs://${configBucket}/BqTail/Rules/case_${parent.index}/'
        credentials: $gcpCredentials


  setupRule:
    action: storage:copy
    expand: true
    source:
      URL: ${parent.path}/rule
    dest:
      credentials: $gcpCredentials
      URL: gs://${configBucket}/BqTail/Rules/case_${parent.index}

  trigger:
    action: storage:copy
    sleepTimeMs: 10000
    source:
      URL: ${parent.path}/data/trigger/
    dest:
      URL: gs://${triggerBucket}/data/case0${parent.index}/
      credentials: $gcpCredentials

