init:
  doneCounter: 0
  parentIndex: ${parent.index}

pipeline:
  prepare:
    init-db:
      action: dsunit:init
      expand: true
      datastore: bqtail
      config:
        driverName: bigquery
        credentials: $gcpCredentials
        parameters:
          datasetId: bqtail
      scripts:
        - URL: ${parent.path}/bqtail/schema.sql
    populate:
      bqtail:
        action: dsunit:prepare
        datastore: bqtail
        URL:  ${parent.path}/bqtail/prepare


  cleanUp:
    action: storage:remove
    sleepTimeMs: 1000
    assets:
      - URL: 'gs://${configBucket}/BqTail/_.cache'
        credentials: $gcpCredentials
      - URL: 'gs://${configBucket}/BqTail/Rules/case_${parent.index}/'
        credentials: $gcpCredentials
      - URL: 'gs://${opsBucket}/BqTail/Journal/Done'
        credentials: $gcpCredentials


  setupRule:
    action: storage:copy
    expand: true
    source:
      URL: ${parent.path}/rule/
    dest:
      credentials: $gcpCredentials
      URL: gs://${configBucket}/BqTail/Rules/case_${parent.index}

  trigger:
    action: storage:copy
    source:
      URL: ${parent.path}/data/trigger/
    dest:
      URL: gs://${triggerBucket}/data/case${parent.index}/
      credentials: $gcpCredentials


  waitForDone:
    listDone:
      init:
        _: $doneCounter++
      action: storage:list
      sleepTimeMs: 10000
      match:
        Filter: 'bqtail.dummy_v${parentIndex}'
      source:
        Credentials: $gcpCredentials
        URL: 'gs://${opsBucket}/BqTail/Journal/Done'

    checkDone:
      action: goto
      when: $Len(${listDone.Assets}) = 0 && $doneCounter < 15
      task: waitForDone

  validate:
    check-db:
      bqtail:
        action: dsunit:expect
        datastore: bqtail
        URL:  ${parent.path}/bqtail/expect
