pipeline:
  set_sdk:
    action: sdk.set
    target: $target
    sdk: go:1.12


  test:
    tag: $pathMatch
    description: '@info'
    subPath: 'cases/${index}_*'
    range: 1..029
    template:
      setVars:
        action: nop
        comments: use case init
        skip: $HasResource(${path}/skip.txt)

      test:
        when: $HasResource(${path}/test.yaml)
        action: run
        request: '@test'


    post-test-sleep:
      action: nop
      sleepTimeMs: 1000
      comments: sleep for extra debuging
