init:
  schemaURL: $Pwd(../mon/schema/schema.sql)
pipeline:
  set_sdk:
    action: sdk.set
    target: $target
    sdk: go:1.12

  init-db:
      expand: true
      action: dsunit:init
      datastore: bqtail
      config:
        driverName: bigquery
        credentials: $gcpCredentials
        parameters:
          datasetId: bqtail
      scripts:
        - URL: $schemaURL

  test:
    tag: $pathMatch
    description: '@info'
    subPath: 'cases/${index}_*'
    range: 1..026
    template:
      setVars:
        action: nop
        comments: use case init
        skip: $HasResource(${path}/skip.txt)

      test:
        when: $HasResource(${path}/test.yaml)
        action: run
        request: '@test'


    post-test-sleep:
      action: nop
      sleepTimeMs: 1000
      comments: sleep for extra debuging
